common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'libreduca' %>
  password: <%= ENV['TRAVIS'] ? '' : 'libreduca' %>

development:
  database: libreduca_development
  host: localhost
  <<: *common

test:
  database: libreduca_test
  host: localhost
  <<: *common

production:
  database: libreduca_production
  host: external_database_host
  <<: *common

sandbox:
  database: libreduca_production
  host: localhost
  <<: *common
